# Generated by Django 4.1.5 on 2023-01-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_userprofile_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='expires_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
